-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS OREILLY_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Database
CREATE DATABASE IF NOT EXISTS OREILLY_DB;

-- Schemas
CREATE SCHEMA IF NOT EXISTS OREILLY_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS OREILLY_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS OREILLY_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS OREILLY_DB.META;

-- Roles
CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;

-- Users
CREATE USER IF NOT EXISTS loader_user
    PASSWORD = 'password'
    DEFAULT_ROLE = LOADER
    DEFAULT_WAREHOUSE = OREILLY_WH;

CREATE USER IF NOT EXISTS transformer_user
    PASSWORD = 'password'
    DEFAULT_ROLE = TRANSFORMER
    DEFAULT_WAREHOUSE = OREILLY_WH;

-- Assign roles to users
GRANT ROLE LOADER TO USER loader_user;
GRANT ROLE TRANSFORMER TO USER transformer_user;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE OREILLY_WH TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE OREILLY_WH TO ROLE TRANSFORMER;

-- Database grants
GRANT USAGE ON DATABASE OREILLY_DB TO ROLE LOADER;
GRANT USAGE ON DATABASE OREILLY_DB TO ROLE TRANSFORMER;

-- Schema grants
GRANT USAGE, CREATE TABLE ON SCHEMA OREILLY_DB.BRONZE TO ROLE LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA OREILLY_DB.META TO ROLE LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA OREILLY_DB.SILVER TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE ON SCHEMA OREILLY_DB.GOLD TO ROLE TRANSFORMER;

-- Table grants
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA OREILLY_DB.META TO ROLE LOADER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA OREILLY_DB.BRONZE TO ROLE LOADER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA OREILLY_DB.SILVER TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA OREILLY_DB.GOLD TO ROLE TRANSFORMER;

-- Tables
CREATE TABLE IF NOT EXISTS OREILLY_DB.BRONZE.RAW_SEARCH_RESULTS (
    raw_payload     VARIANT,
    ingested_at     TIMESTAMP,
    watermark       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OREILLY_DB.META.PIPELINE_WATERMARKS (
    pipeline_name   VARCHAR,
    last_watermark  TIMESTAMP,
    updated_at      TIMESTAMP
);